version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CJvkaczJkwYTOcYKfHpbPFNHVfHqJkiF
      POSTGRES_DB: railway
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - loan-tracking-network
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PUBLIC_URL=postgresql://postgres:CJvkaczJkwYTOcYKfHpbPFNHVfHqJkiF@postgres.railway.internal:5432/railway
    depends_on:
      - db
    networks:
      - loan-tracking-network

networks:
  loan-tracking-network:
    driver: bridge

volumes:
  db_data:
